// <auto-generated />
using System;
using Core.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Infra.Data.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20200215192705_ParteInteressada")]
    partial class ParteInteressada
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Business.Entities.Identity.Perfil", b =>
                {
                    b.Property<int>("PERFIL_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NOME")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("PERFIL_ID");

                    b.ToTable("T000_PERFIL");
                });

            modelBuilder.Entity("Core.Business.Entities.Identity.Usuario", b =>
                {
                    b.Property<string>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MATRICULA")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("CodigoUnidade")
                        .HasColumnName("NU_UNID_ADM");

                    b.Property<bool>("FLAG_ATIVO");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("NomeUnidade")
                        .HasColumnName("SG_UNID_ADM")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Matricula");

                    b.ToTable("T000_USUARIOS");
                });

            modelBuilder.Entity("Core.Business.Entities.Identity.UsuarioAcesso", b =>
                {
                    b.Property<string>("MATRICULA")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("MATRICULA");

                    b.ToTable("T000_USUARIO_ACESSO");
                });

            modelBuilder.Entity("Core.Business.Entities.Identity.UsuarioPerfil", b =>
                {
                    b.Property<string>("MATRICULA")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("PERFIL_ID");

                    b.HasKey("MATRICULA", "PERFIL_ID");

                    b.HasIndex("PERFIL_ID");

                    b.ToTable("T000_USUARIO_PERFIL");
                });

            modelBuilder.Entity("Core.Business.Entities.Identity.UsuarioVinculado", b =>
                {
                    b.Property<string>("MATRICULA_GERENTE")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("MATRICULA_VINCULO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("MATRICULA_GERENTE", "MATRICULA_VINCULO");

                    b.HasIndex("MATRICULA_VINCULO");

                    b.ToTable("T000_USUARIO_VINCULADO");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Arquivo", b =>
                {
                    b.Property<int>("CO_ARQUIVO")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CO_PROJETO");

                    b.Property<DateTime>("DT_CADASTRO");

                    b.Property<string>("ENDERECO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("NOME")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("CO_ARQUIVO");

                    b.HasIndex("CO_PROJETO");

                    b.ToTable("T012_ARQUIVOS");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Beneficio", b =>
                {
                    b.Property<int>("CO_BENEFICIO")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CO_PROJETO");

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime>("DT_CADASTRO");

                    b.HasKey("CO_BENEFICIO");

                    b.HasIndex("CO_PROJETO");

                    b.ToTable("T009_BENEFICIOS");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Custo", b =>
                {
                    b.Property<int>("CO_CUSTO")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CO_PROJETO");

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime>("DT_CADASTRO");

                    b.Property<decimal>("VALOR");

                    b.HasKey("CO_CUSTO");

                    b.HasIndex("CO_PROJETO");

                    b.ToTable("T005_CUSTOS");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Justificativa", b =>
                {
                    b.Property<int>("CO_JUSTIFICATIVA")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CO_PROJETO");

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime>("DT_CADASTRO");

                    b.HasKey("CO_JUSTIFICATIVA");

                    b.HasIndex("CO_PROJETO");

                    b.ToTable("T006_JUSTIFICATIVAS");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.MarcosEntrega", b =>
                {
                    b.Property<int>("CO_MARCOS_ENTREGA")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CO_PROJETO");

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime>("DT_CADASTRO");

                    b.HasKey("CO_MARCOS_ENTREGA");

                    b.HasIndex("CO_PROJETO");

                    b.ToTable("T011_MARCOS_ENTREGAS");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Objetivo", b =>
                {
                    b.Property<int>("CO_OBJETIVO")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CO_PROJETO");

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime>("DT_CADASTRO");

                    b.HasKey("CO_OBJETIVO");

                    b.HasIndex("CO_PROJETO");

                    b.ToTable("T004_OBJETIVOS");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.ParteInteressada", b =>
                {
                    b.Property<int>("CO_PARTE")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CGC_UND");

                    b.Property<int>("CO_PROJETO");

                    b.Property<DateTime>("DT_CADASTRO");

                    b.HasKey("CO_PARTE");

                    b.HasIndex("CO_PROJETO");

                    b.ToTable("T013_PARTES_INTERESSADAS");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Premissa", b =>
                {
                    b.Property<int>("CO_PREMISSA")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CO_PROJETO");

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime>("DT_CADASTRO");

                    b.HasKey("CO_PREMISSA");

                    b.HasIndex("CO_PROJETO");

                    b.ToTable("T010_PREMISSAS");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Projeto", b =>
                {
                    b.Property<int>("CO_PROJETO")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CAIXA_POSTAL")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("CO_STATUS");

                    b.Property<int>("CO_TIPO");

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime>("DT_CADASTRO");

                    b.Property<DateTime?>("DT_FIM");

                    b.Property<DateTime?>("DT_INICIO");

                    b.Property<string>("GESTOR_DEMANDANTE")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("MATRICULA_GERENTE")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("MATRICULA_PATROCINADOR")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("NOME")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("OBSERVACAO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<decimal?>("PERCENTUAL");

                    b.HasKey("CO_PROJETO");

                    b.HasIndex("CO_STATUS");

                    b.HasIndex("CO_TIPO");

                    b.HasIndex("MATRICULA_GERENTE");

                    b.HasIndex("MATRICULA_PATROCINADOR");

                    b.ToTable("T003_PROJETOS");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Restricao", b =>
                {
                    b.Property<int>("CO_RESTRICAO")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CO_PROJETO");

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime>("DT_CADASTRO");

                    b.HasKey("CO_RESTRICAO");

                    b.HasIndex("CO_PROJETO");

                    b.ToTable("T007_RESTRICOES");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Risco", b =>
                {
                    b.Property<int>("CO_RISCO")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CO_PROJETO");

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime>("DT_CADASTRO");

                    b.HasKey("CO_RISCO");

                    b.HasIndex("CO_PROJETO");

                    b.ToTable("T008_RISCOS");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.StatusProjeto", b =>
                {
                    b.Property<int>("CO_STATUS")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("CO_STATUS");

                    b.ToTable("T002_STATUS_PROJETO");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.TipoProjeto", b =>
                {
                    b.Property<int>("CO_TIPO")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("CO_TIPO");

                    b.ToTable("T001_TIPO_PROJETO");
                });

            modelBuilder.Entity("Core.Business.Entities.Identity.UsuarioAcesso", b =>
                {
                    b.HasOne("Core.Business.Entities.Identity.Usuario", "Usuario")
                        .WithMany("UsuariosAcesso")
                        .HasForeignKey("MATRICULA")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Business.Entities.Identity.UsuarioPerfil", b =>
                {
                    b.HasOne("Core.Business.Entities.Identity.UsuarioAcesso", "UsuarioAcesso")
                        .WithMany("UsuariosPerfis")
                        .HasForeignKey("MATRICULA")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Business.Entities.Identity.Perfil", "Perfil")
                        .WithMany("UsuarioPerfis")
                        .HasForeignKey("PERFIL_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Business.Entities.Identity.UsuarioVinculado", b =>
                {
                    b.HasOne("Core.Business.Entities.Identity.UsuarioAcesso", "UsuarioAcesso")
                        .WithMany("UsuariosVinculados")
                        .HasForeignKey("MATRICULA_GERENTE")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Business.Entities.Identity.Usuario", "Vinculo")
                        .WithMany("UsuariosVinculados")
                        .HasForeignKey("MATRICULA_VINCULO")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Arquivo", b =>
                {
                    b.HasOne("Core.Business.Entities.Projetos.Projeto", "Projeto")
                        .WithMany("Arquivos")
                        .HasForeignKey("CO_PROJETO")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Beneficio", b =>
                {
                    b.HasOne("Core.Business.Entities.Projetos.Projeto", "Projeto")
                        .WithMany("Beneficios")
                        .HasForeignKey("CO_PROJETO")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Custo", b =>
                {
                    b.HasOne("Core.Business.Entities.Projetos.Projeto", "Projeto")
                        .WithMany("Custos")
                        .HasForeignKey("CO_PROJETO")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Justificativa", b =>
                {
                    b.HasOne("Core.Business.Entities.Projetos.Projeto", "Projeto")
                        .WithMany("Justificativas")
                        .HasForeignKey("CO_PROJETO")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.MarcosEntrega", b =>
                {
                    b.HasOne("Core.Business.Entities.Projetos.Projeto", "Projeto")
                        .WithMany("MarcosEntregas")
                        .HasForeignKey("CO_PROJETO")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Objetivo", b =>
                {
                    b.HasOne("Core.Business.Entities.Projetos.Projeto", "Projeto")
                        .WithMany("Objetivos")
                        .HasForeignKey("CO_PROJETO")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.ParteInteressada", b =>
                {
                    b.HasOne("Core.Business.Entities.Projetos.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("CO_PROJETO")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Premissa", b =>
                {
                    b.HasOne("Core.Business.Entities.Projetos.Projeto", "Projeto")
                        .WithMany("Premissas")
                        .HasForeignKey("CO_PROJETO")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Projeto", b =>
                {
                    b.HasOne("Core.Business.Entities.Projetos.StatusProjeto", "StatusProjeto")
                        .WithMany("Projetos")
                        .HasForeignKey("CO_STATUS")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Business.Entities.Projetos.TipoProjeto", "TipoProjeto")
                        .WithMany("Projetos")
                        .HasForeignKey("CO_TIPO")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Business.Entities.Identity.Usuario", "Gerente")
                        .WithMany("ProjetosGerente")
                        .HasForeignKey("MATRICULA_GERENTE");

                    b.HasOne("Core.Business.Entities.Identity.Usuario", "Patrocinador")
                        .WithMany("ProjetosPatrocinador")
                        .HasForeignKey("MATRICULA_PATROCINADOR");
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Restricao", b =>
                {
                    b.HasOne("Core.Business.Entities.Projetos.Projeto", "Projeto")
                        .WithMany("Restricoes")
                        .HasForeignKey("CO_PROJETO")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Business.Entities.Projetos.Risco", b =>
                {
                    b.HasOne("Core.Business.Entities.Projetos.Projeto", "Projeto")
                        .WithMany("Riscos")
                        .HasForeignKey("CO_PROJETO")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
